server:
  port: 8080

service:
  name: formunity-backend

database:
  addr: ${DATABASE_ADDR}
  port: ${DATABASE_PORT}
  db-name: ${DATABASE_NAME}
  user: ${DATABASE_USER}
  pass: ${DATABASE_PASS}
  insecure: ${DATABASE_INSECURE}
  pool: 6
  timeout: 5

oauth:
  secret: ${OAUTH_SECRET}